# version: '3.8'

# services:
#   backend:
#     build: 
#       context: .
#       target: builder
#     ports:
#       - "8000:8000"
#     environment:
#       - NODE_ENV=production
#       - PORT=8000
#     volumes:
#       - ./logs:/usr/src/app/logs
#     restart: always


version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env