export function buildSessionReportCsv(params: {
  sessions: Array<{
    _id: any;
    title: string;
    description: string;
    topics?: string[];
    sessionDate: Date;
    startTime: Date;
    duration: number;
    price: number;
    status: string;
    paymentStatus: string;
    rejectionReason?: string;
    createdAt?: Date;
    updatedAt?: Date;
    user: { _id: any; username: string; email: string };
    developer: { _id: any; username: string; email: string };
  }>;
  totals: { count: number; amount: number };
  filters: { status: string[]; search?: string; from?: string; to?: string };
}) {
  const { sessions, totals, filters } = params;
  const lines: string[] = [];

  const fmt = (d?: Date | string) => (d ? new Date(d).toISOString() : "");

  lines.push("Report Name: Session Report");
  lines.push(`Generated At: ${fmt(new Date())}`);
  lines.push("Generated By: Admin");
  lines.push(
    `Filters Applied: Status=${filters.status.join("|")}${filters.search ? `; Search=${filters.search}` : ""}${filters.from ? `; From=${filters.from}` : ""}${filters.to ? `; To=${filters.to}` : ""}`,
  );
  lines.push(`Total Sessions: ${totals.count}`);
  lines.push(`Total Amount: ${totals.amount}`);
  lines.push("");

  lines.push(
    [
      "Session ID",
      "Title",
      "Topics",
      "Session Date",
      "Start Time",
      "Duration (min)",
      "Status",
      "Payment Status",
      "Amount",
      "User ID",
      "User Username",
      "User Email",
      "Developer ID",
      "Developer Username",
      "Developer Email",
      "Rejection Reason",
      "Created At",
      "Updated At",
    ].join(","),
  );

  for (const s of sessions) {
    lines.push(
      [
        s._id,
        safe(s.title),
        safe((s.topics || []).join("|")),
        fmt(s.sessionDate),
        fmt(s.startTime),
        s.duration,
        s.status,
        s.paymentStatus,
        s.price,
        s.user?._id ?? "",
        safe(s.user?.username ?? ""),
        safe(s.user?.email ?? ""),
        s.developer?._id ?? "",
        safe(s.developer?.username ?? ""),
        safe(s.developer?.email ?? ""),
        safe(s.rejectionReason ?? ""),
        fmt(s.createdAt),
        fmt(s.updatedAt),
      ].join(","),
    );
  }

  return lines.join("\n");

  function safe(val: string) {
    if (val == null) return "";
    const needsQuotes = /[",\n]/.test(val);
    const escaped = val.replace(/"/g, '""');
    return needsQuotes ? `"${escaped}"` : escaped;
  }
}
